services:
  findingaid:
    build:
      target: development
    environment:
      APP_ENV: development
    develop:
      watch:
        - action: restart
          path: ./app
          target: /opt/findingaid/app
