#!/bin/bash
set -euo pipefail

# The environment should provide these variables
# SOLR_URL: e.g. https://solrhost.example.com/solr/select

ARKS_FILE="$(mktemp)"
export ARKS_FILE

trap 'rm -f "$ARKS_FILE"' EXIT

echo "Generating list of finding aids to reprocess"
SOLR_URL=$SOLR_URL fetch-ead-arks.sh
echo "Reprocessing finding aids"
xargs -n 1 -P 4 fa-regen < "$ARKS_FILE"
